spring:
  application:
    name: poc-response-api
  kafka:
    consumer:
#      bootstrap-servers: localhost:29092 quando executada em localhost e não dockerizada
      bootstrap-servers: kafka:9092
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            use:
              type:
                headers: false
            value:
              default:
                type: br.com.tomwell.poc_response_api.dto.QuoteRequest
            trusted:
              packages: '*'

server:
  port: 8082
  servlet:
    context-path: /poc-response-api

logging:
  level:
    root: INFO